spring.application.name=backend_spring
<<<<<<< HEAD
server.port=8080

# H2
spring.datasource.url=jdbc:h2:mem:deepfake_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Multipart
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Custom
app.upload-dir=uploads
app.ai-server-url=http://localhost:8000/predict
=======
>>>>>>> 27b720b76c5e38c34c231e80da5ad80270c78581
